sudo: false  # run on new infrastructure
language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"
matrix:
  allow_failures:
    - python: "3.2"
    - python: "pypy"
    - python: "pypy3"
install:
  - "python -m pip install pip --upgrade"
  - "pip install ."
  - "pip install .[ical]"
  - "pip install .[test]"
  - "pip install codecov"
script:
  - "green -vvr"
  - "python -m pylint --errors-only topydo test"
# Cache Dependencies
after_script:
  - codecov
cache:
  directories:
    - $HOME/travis/.cache/pip
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b7a69031304c472294ac
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
