sudo: false  # run on new infrastructure
language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"
matrix:
  allow_failures:
    - python: "3.2"
    - python: "pypy"
    - python: "pypy3"
install:
  - "pip install ."
  - "pip install icalendar"
  - "pip install pylint"
script: "./run-tests.sh"
# Cache Dependencies
cache:
  directories:
    - $HOME/travis/.cache/pip
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b7a69031304c472294ac
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
